name: rock_weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  equatable: ^1.2.5
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  intl: ^0.16.1
  json_annotation: ^3.1.1
  hello:
    git:
      url: ssh://aveit@github.com/aveit/hello.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  test: ^1.15.7
  mockito: ^4.1.3
  freezed: ^0.12.6
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
