# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Dart

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.0
      with:
        key: ${{ secrets.SSH_GITHUB_ACTIONS }}
        #name: id_rsa # optional
        known_hosts: unnecessary
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
        # Setup the flutter environment.
        
    - name: Get flutter depencencies
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1.5.0
      with:
        # channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '1.22.6' # you can also specify exact version of flutter

    # Get flutter dependencies.
    - run: flutter pub get
